### ISSUE TITLE
Color correction for quoted text

### ISSUE THREAD

**Issue by dpinkus** [learn-co-curriculum/puts-print-and-return-readme#13]
I don't know how to fix this myself or I would have submitted it.  Starting with the apostrophe, the 's Johnny! text is red, but the Here text is black.

Here's Johnny!
=> nil

![image](https://cloud.githubusercontent.com/assets/847344/9503568/fb3ba27c-4bf4-11e5-919b-2d11118ad4e9.png)

You might consider showing the invocation also (you tell students to do it in the text, but it doesn't appear in code).

**Comment by AnnJohn** [comment]
@dpinkus Thanks for raising this issue.

**Comment by SophieDeBenedetto** [comment]
thanks @dpinkus, all fixed!
