### ISSUE TITLE
link "table above" opens up a new tab

### ISSUE THREAD

**Issue by kucher12** [learn-co-curriculum/puts-print-and-return-readme#23]
The link in the text "table above" has a ' target = "_blank" ' on it in HTML, which opens it in the new tab instead of just jumping back up to the table on the page. 

While on github it work ok, on the actual learn.co site - it opens a new tab.

It is a small thing, but I think it could be fixed.

**Comment by AnnJohn** [comment]
thanks @kucher12; we just removed the hyperlink.
