### ISSUE TITLE
Ask a Question trouble

### ISSUE THREAD

**Issue by bhabig** [learn-co-curriculum/puts-print-and-return-readme#26]
I am not seeing everything being said in the conversation in the main window. there is what looks like a minimized window bar for the question next to the text entry box as well, and i can't open that when i click the arrow. 
![ask a question](https://cloud.githubusercontent.com/assets/17533183/15193766/7f4fcb4c-178d-11e6-8dbb-59adba48d909.PNG)

**Comment by AnnJohn** [comment]
hi @bhabig can you please file a bug report as this is a technical issue. We use this space for issues specifically related to curriculum content. 

Thanks!
