### ISSUE TITLE
IRB doesn't return the value it supposed to return.

### ISSUE THREAD

**Issue by lilythevalley** [learn-co-curriculum/puts-print-and-return-readme#28]
```
def stylish_chef
  best_hairstyle = "Guy Fieri"
  return "Martha Stewart"
  "Guy Fieri"
end

```
by copy and pasting this code above into IRB, 
it returns 

`=> :stylish_chef` 
instead of "Martha Stewart"

rest of the IRB practices are same

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the _content_ of this lesson. If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by lilythevalley** [comment]
Okay thank you.

**Comment by AnnJohn** [comment]
hi @lilythevalley, after you enter it into IRB, you need to then enter in the function name- stylish_chef

this will return 'Martha Stewart'

Thanks!
