### ISSUE TITLE
I think there is a typo in the lesson

### ISSUE THREAD

**Issue by SophiaGrace16** [learn-co-curriculum/puts-print-and-return-readme#35]
**What** methods like puts and print allow us to output to the console is different from Ruby's concept of a return value.
I think the word What is supposed to be while? I wasn't sure though!

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
