### ISSUE TITLE
Lots of reading 

### ISSUE THREAD

**Issue by aenbar** [learn-co-curriculum/puts-print-and-return-readme#5]
this, plus the three lessons before it, were all readmes. Not super long, but it's a lot to digest, especially since one have a 12 min video. May be worth inserting a lab somewhere (maybe on methods or method arguments) to keep people engaged.

**Comment by BenjaGross** [comment]
@SophieDeBenedetto Do we want to add a REPL exercise on one of these? It seems to early to bring in any labs about methods or arguments.

**Comment by SophieDeBenedetto** [comment]
I agree. We can't add REPL to anything that uses `puts` yet but can definitely add either a variable assignment or basic method repl to one of the previous lessons and some "code along" like IRB suggestions to this one.

**Comment by SophieDeBenedetto** [comment]
added code along exercise to this readme and series of repls to the two previous readmes. waiting to deploy due to repl bugs. closing this issue
