### ISSUE TITLE
Math is off?

### ISSUE THREAD

**Issue by joelehr** [learn-co-curriculum/puts-print-and-return-readme#7]
====
In IRB, type: 6 + 3

You should see a return value of => 9
Now, set a variable total equal to 6 + 3.

You've just stored the return value of adding 6 and 3 and you can now grab that return value 9 by referencing the total variable.
Set another variable, new_total equal to total + 10.

You should see a return value of 18.
====

shouldnt return value be 19?

**Comment by sammarcus** [comment]
Fixed in 4868b5012e19a813fa52e801a14175f795da3426! Thanks @joelehr
